<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access request' => '',
    'Contact' => '',
    'Files' => '',
    'Folder' => '',
    'Proposal' => '',
    'Room' => '',
    'Room image' => '',
    'Room specific' => '',
    'Active' => 'Activé',
    'Comment' => 'Commenter',
    'Cover Letter' => 'Lettre de motivation',
    'Download' => 'Télécharger',
    'Download current document' => 'Télécharger ce document',
    'File' => 'Fichier',
    'File(s)' => 'Fichier(s)',
    'ID' => 'ID',
    'Link' => 'Lien',
    'Not Published' => 'Non publié',
    'Order' => 'Ordre',
    'Publish Date' => 'Date de publication',
    'Published' => 'Publié',
    'Regular' => 'Normal',
    'Resume' => 'Recommencer',
    'Size' => 'Poids',
    'Title' => 'Titre',
    'Today' => 'Aujourd\'hui',
    'Type' => 'Type',
    'Updated Date' => 'Date de mise à jour',
    'Void' => 'Vide',
];
