<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Comment' => 'Commentaire',
    'Date' => 'Date',
    'Error when saving history.' => 'Erreur lors de la sauvegarde de l\'historique.',
    'Full Data' => 'Données complètes',
    'History Comment' => 'Historique des commentaires',
    'ID' => 'ID',
    'Is Admin' => 'Est Administrateur',
    'Model' => 'Modèle',
    'New Value:' => 'Nouvelle valeur:',
    'New record' => 'Nouvelle enregistrement:',
    'Old Value:' => 'Ancienne valeur:',
    'Record ID' => 'ID Enregistrement',
    'Table' => 'Tableau',
    'Type' => 'Type',
    'Updated By' => 'Mis à jour par',
    'Updated Fields' => 'Champs mis à jour',
    '[Guest]' => '[Guest]',
];
