<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Attachment' => 'Pièces jointe',
    'Madam' => 'Madame',
    'Master' => 'Maître',
    'Name of the mandate' => 'Nom du dossier',
    'Sir' => 'Monsieur',
    '- Choose template to load -' => '- Choisir le modèle à charger -',
    'Body' => 'Message',
    'Civility' => 'Civilité',
    'Closed' => 'Fermé',
    'Code' => 'Code',
    'Company' => 'Entreprise',
    'Contact' => 'Formulaire de contact',
    'Contact ID' => 'ID',
    'Contact Templates' => 'Modèles de formulaires de contact',
    'Contact Type' => 'Type',
    'Cover Letter' => 'Lettre de motivation',
    'Created Date' => 'Date de création',
    'Email' => 'Email',
    'Error when saving new template! Please close dialog and try again.' => 'Erreur lors de la sauvegarde du nouveau modèle! veuillez fermer cette fenêtre et réessayer.',
    'First Name' => 'Prénom',
    'From User ID' => 'ID Formulaire utilisateur',
    'ID' => 'ID',
    'Is Last Message' => 'Est le dernier message',
    'Last Name' => 'Nom',
    'Load' => 'Charger',
    'Manage templates' => 'Gérer les modèles',
    'Message' => 'Message',
    'Name' => 'Nom',
    'New reply' => 'Nouvelle réponse',
    'New template has been successfully created.' => 'Le nouveau modèle a bien été créé.',
    'New template {name}' => 'Nouveau modèle {name}',
    'Not available' => 'Indisponible',
    'Opened' => 'Ouvert',
    'Phone' => 'Téléphone',
    'Responses' => 'Réponses',
    'Resume' => 'CV',
    'Réponses' => 'Réponses',
    'Save as a new template' => 'Sauvegarder en tant que nouveau modèle',
    'Save template' => 'Sauvgarder le modèle',
    'Sender' => 'Expéditeur',
    'Subject' => 'Sujet',
    'Subscribe to news' => 'S\'inscrire aux actualités',
    'Telephone' => 'Téléphone',
    'Template' => 'Modèle',
    'Template Body' => 'Corps',
    'Template preview' => 'Prévisualiser le modèle',
    'Template successfully saved.' => 'Le modèle a bien été sauvegardé.',
    'Templates' => 'Modèles',
    'There was an error during sending email. Email not sent.' => 'Une erreur est survenue durant l\'envoi de l\'email. Email non envoyé.',
    'This topic is closed.' => 'Ce sujet est clos.',
    'This topic is closed. Please open it to be able to send a new reply.' => 'Ce sujet est clos. veuillez l\'ouvrir pour pouvoir envoyer une nouvelle réponse.',
    'To User ID' => 'A ID Utilisateur',
    'Type' => 'Type',
    'User profile' => 'Profil Utilisateur',
    'Verify Code' => 'Code de vérification',
    'Your message has been sent.' => 'Votre message a bien été envoyé.',
    'Send' => 'Envoyer',
];
