<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Results of the form {formName} - {formDate}' => '',
    'Results of the form "{formName}" - {formDate}' => '@@Résulats du formulaire "{formName}" - {formDate}@@',
    ' - Please select - ' => '- Séléctionnez -',
    'Available tags' => 'Balises disponibles',
    'Body' => 'Corps',
    'Close thread' => 'Fermer le fil',
    'Comments' => 'Commentaires',
    'Default' => 'Défaut',
    'Delete' => 'Supprimer',
    'Documents' => 'Documents',
    'Event' => 'Evènement',
    'Find answers to your forms on your back office' => 'Retrouvez les réponses à vos formulaires sur votre backoffice',
    'Is Default' => 'Est Par défaut',
    'News' => 'Actualités',
    'Not Default' => 'Pas Par défaut',
    'Notifications' => 'Notifications',
    'Open thread' => 'Ouvrir le fil',
    'Option deleted' => 'Option supprimée',
    'Parameters' => 'Paramètres',
    'Priority' => 'Priorité',
    'Put to Queue' => 'Mettre en attente',
    'Subject' => 'Objet',
    'Title' => 'Titre',
    'Updated Date' => 'Date de mise à jour',
];
