<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '10% width column' => '',
    '16% width column' => '',
    '20% width column' => '',
    '25% width column' => '',
    '33% width column' => '',
    '40% width column' => '',
    '60% width column' => '',
    '66% width column' => '',
    '75% width column' => '',
    '80% width column' => '',
    'Are you sure you want to copy this page ?' => '',
    'Are you sure you want to delete selected pages?' => '',
    'Button' => '',
    'Cell data' => '',
    'Choose Image' => '',
    'Close' => '',
    'Collapse' => '',
    'Collapse All' => '',
    'Column' => '',
    'Content Elements' => '',
    'Copy' => '',
    'Copy page' => '',
    'Copy section' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Date de prise du poste' => '',
    'Delete column' => '',
    'Delete section' => '',
    'Delete selected' => '',
    'Done' => '',
    'Drag & Drop Files' => '',
    'Dynamic' => '',
    'Dynamic block' => '',
    'Edit' => '',
    'Edit section' => '',
    'Email' => '',
    'Expand' => '',
    'Expand All' => '',
    'Full width column' => '',
    'Half width column' => '',
    'Header text' => '',
    'Icon Box' => '',
    'Icon List' => '',
    'Image' => '',
    'Image Caption' => '',
    'Image preview' => '',
    'Job title of the person' => '',
    'Layout Elements' => '',
    'Lien vers la page de l\'associé' => '',
    'Link' => '',
    'List Item' => '',
    'List item' => '',
    'Name of the person' => '',
    'N° de téléphone' => '',
    'Or choose an existing one' => '',
    'Or put an image URL' => '',
    'Preview' => '',
    'Redo changes (ctrl + shift + z)' => '',
    'Save changes' => '',
    'Section' => '',
    'Separator' => '',
    'Slider' => '',
    'Styles and scripts' => '',
    'Table' => '',
    'Team Member' => '',
    'Team Member Image' => '',
    'Team Member Job title' => '',
    'Team Member Name' => '',
    'Text' => '',
    'Text Block' => '',
    'Trendy Page' => '',
    'Trendy Pages' => '',
    'Undo changes (ctrl + z)' => '',
    'Update' => '',
    'Update & Close' => '',
    'Upload' => '',
    'Upload image' => '',
    'Video' => '',
    'Phone Number' => '@@@@',
    'Phone number' => '@@@@',
];
